export const GENRES = [
  "Action",
  "Adventure",
  "Cars",
  "Comedy",
  "Dementia",
  "Demons",
  "Drama",
  "Ecchi",
  "Fantasy",
  "Game",
  "Gender Bender",
  "Harem",
  "Hentai",
  "Historical",
  "Horror",
  "Isekai",
  "Josei",
  "Kids",
  "Magic",
  "Martial Arts",
  "Mecha",
  "Military",
  "Music",
  "Mystery",
  "Parody",
  "Police",
  "Psychological",
  "Romance",
  "Samurai",
  "School",
  "Sci-Fi",
  "Seinen",
  "Shoujo",
  "Shoujo Ai",
  "Shounen",
  "Shounen Ai",
  "Slice of Life",
  "Space",
  "Sports",
  "Super Power",
  "Supernatural",
  "Thriller",
  "Tragedy",
  "Vampire",
  "Yaoi",
  "Yuri",
];

export const TYPES = [
  { id: "all", label: "All" },
  { id: "manga", label: "Manga" },
  { id: "novel", label: "Novel" },
  { id: "one-shot", label: "One-Shot" },
  { id: "doujinshi", label: "Doujinshi" },
  { id: "manhwa", label: "Manhwa" },
  { id: "manhua", label: "Manhua" },
  { id: "oel", label: "OEL" },
];

export const STATUS = [
  { id: "all", label: "All" },
  { id: "publishing", label: "Publishing" },
  { id: "finished", label: "Finished" },
  { id: "on hiatus", label: "On Hiatus" },
  { id: "discontinued", label: "Discontinued" },
  { id: "not yet published", label: "Not Yet Published" },
];
