import { SearchSort, Tag } from "@suwatte/daisuke";

export const CONTENT_TYPE_TAGS: Tag[] = [
  { id: "genre:artbook", label: "Artbook", adultContent: false },
  { id: "genre:cartoon", label: "Cartoon", adultContent: false },
  { id: "genre:comic", label: "Comic", adultContent: false },
  { id: "genre:doujinshi", label: "Doujinshi", adultContent: false },
  { id: "genre:imageset", label: "Imageset", adultContent: false },
  { id: "genre:manga", label: "Manga", adultContent: false },
  { id: "genre:manhua", label: "Manhua", adultContent: false },
  { id: "genre:manhwa", label: "Manhwa", adultContent: false },
  { id: "genre:webtoon", label: "Webtoon", adultContent: false },
  { id: "genre:western", label: "Western", adultContent: false },
];

export const DEMOGRAPHIC_TAGS: Tag[] = [
  { id: "genre:shoujo", label: "Shoujo(G)", adultContent: false },
  { id: "genre:shounen", label: "Shounen(B)", adultContent: false },
  { id: "genre:josei", label: "Josei(W)", adultContent: false },
  { id: "genre:seinen", label: "Seinen(M)", adultContent: false },
  { id: "genre:yuri", label: "Yuri(GL)", adultContent: false },
  { id: "genre:yaoi", label: "Yaoi(BL)", adultContent: false },
  { id: "genre:futa", label: "Futa(WL)", adultContent: true },
  { id: "genre:bara", label: "Bara(ML)", adultContent: true },
];

export const ADULT_TAGS: Tag[] = [
  { id: "genre:gore", label: "Gore", adultContent: true },
  { id: "genre:bloody", label: "Bloody", adultContent: true },
  { id: "genre:violence", label: "Violence", adultContent: true },
  { id: "genre:ecchi", label: "Ecchi", adultContent: true },
  { id: "genre:adult", label: "Adult", adultContent: true },
  { id: "genre:mature", label: "Mature", adultContent: true },
  { id: "genre:smut", label: "Smut", adultContent: true },
  { id: "genre:hentai", label: "Hentai", adultContent: true },
];

export const GENERIC_TAGS: Tag[] = [
  { id: "genre:_4_koma", label: "4-Koma", adultContent: false },
  { id: "genre:action", label: "Action", adultContent: false },
  { id: "genre:adaptation", label: "Adaptation", adultContent: false },
  { id: "genre:adventure", label: "Adventure", adultContent: false },
  { id: "genre:age_gap", label: "Age Gap", adultContent: false },
  { id: "genre:aliens", label: "Aliens", adultContent: false },
  { id: "genre:animals", label: "Animals", adultContent: false },
  { id: "genre:anthology", label: "Anthology", adultContent: false },
  { id: "genre:beasts", label: "Beasts", adultContent: false },
  { id: "genre:bodyswap", label: "Bodyswap", adultContent: false },
  { id: "genre:cars", label: "Cars", adultContent: false },
  {
    id: "genre:cheating_infidelity",
    label: "Cheating/Infidelity",
    adultContent: false,
  },
  {
    id: "genre:childhood_friends",
    label: "Childhood Friends",
    adultContent: false,
  },
  { id: "genre:college_life", label: "College life ", adultContent: false },
  { id: "genre:comedy", label: "Comedy", adultContent: false },
  {
    id: "genre:contest_winning",
    label: "Contest winning",
    adultContent: false,
  },
  { id: "genre:cooking", label: "Cooking", adultContent: false },
  { id: "genre:crime", label: "Crime", adultContent: false },
  { id: "genre:crossdressing", label: "Crossdressing", adultContent: false },
  { id: "genre:delinquents", label: "Delinquents", adultContent: false },
  { id: "genre:dementia", label: "Dementia", adultContent: false },
  { id: "genre:demons", label: "Demons", adultContent: false },
  { id: "genre:drama", label: "Drama", adultContent: false },
  { id: "genre:dungeons", label: "Dungeons", adultContent: false },
  {
    id: "genre:emperor_daughte",
    label: "Emperor's daughte",
    adultContent: false,
  },
  { id: "genre:fantasy", label: "Fantasy", adultContent: false },
  { id: "genre:fan_colored", label: "Fan-Colored", adultContent: false },
  { id: "genre:fetish", label: "Fetish", adultContent: false },
  { id: "genre:full_color", label: "Full Color", adultContent: false },
  { id: "genre:game", label: "Game", adultContent: false },
  { id: "genre:gender_bender", label: "Gender Bender", adultContent: false },
  { id: "genre:genderswap", label: "Genderswap", adultContent: false },
  { id: "genre:ghosts", label: "Ghosts", adultContent: false },
  { id: "genre:gyaru", label: "Gyaru", adultContent: false },
  { id: "genre:harem", label: "Harem", adultContent: false },
  { id: "genre:harlequin", label: "Harlequin", adultContent: false },
  { id: "genre:historical", label: "Historical", adultContent: false },
  { id: "genre:horror", label: "Horror", adultContent: false },
  { id: "genre:incest", label: "Incest", adultContent: false },
  { id: "genre:isekai", label: "Isekai", adultContent: false },
  { id: "genre:kids", label: "Kids", adultContent: false },
  { id: "genre:loli", label: "Loli", adultContent: false },
  { id: "genre:magic", label: "Magic", adultContent: false },
  { id: "genre:magical_girls", label: "Magical Girls", adultContent: false },
  { id: "genre:martial_arts", label: "Martial Arts", adultContent: false },
  { id: "genre:mecha", label: "Mecha", adultContent: false },
  { id: "genre:medical", label: "Medical", adultContent: false },
  { id: "genre:military", label: "Military", adultContent: false },
  { id: "genre:monster_girls", label: "Monster Girls", adultContent: false },
  { id: "genre:monsters", label: "Monsters", adultContent: false },
  { id: "genre:music", label: "Music", adultContent: false },
  { id: "genre:mystery", label: "Mystery", adultContent: false },
  { id: "genre:netorare", label: "Netorare/NTR", adultContent: false },
  { id: "genre:ninja", label: "Ninja", adultContent: false },
  { id: "genre:office_workers", label: "Office Workers", adultContent: false },
  { id: "genre:omegaverse", label: "Omegaverse", adultContent: false },
  { id: "genre:oneshot", label: "Oneshot", adultContent: false },
  { id: "genre:parody", label: "parody", adultContent: false },
  { id: "genre:philosophical", label: "Philosophical", adultContent: false },
  { id: "genre:police", label: "Police", adultContent: false },
  {
    id: "genre:post_apocalyptic",
    label: "Post-Apocalyptic",
    adultContent: false,
  },
  { id: "genre:psychological", label: "Psychological", adultContent: false },
  { id: "genre:regression", label: "Regression", adultContent: false },
  { id: "genre:reincarnation", label: "Reincarnation", adultContent: false },
  { id: "genre:reverse_harem", label: "Reverse Harem", adultContent: false },
  { id: "genre:revenge", label: "Revenge", adultContent: false },
  { id: "genre:reverse_isekai", label: "Reverse Isekai ", adultContent: false },
  { id: "genre:romance", label: "Romance", adultContent: false },
  { id: "genre:royal_family", label: "Royal family", adultContent: false },
  { id: "genre:royalty", label: "Royalty", adultContent: false },
  { id: "genre:samurai", label: "Samurai", adultContent: false },
  { id: "genre:school_life", label: "School Life", adultContent: false },
  { id: "genre:sci_fi", label: "Sci-Fi", adultContent: false },
  { id: "genre:shota", label: "Shota", adultContent: false },
  { id: "genre:shoujo_ai", label: "Shoujo ai", adultContent: false },
  { id: "genre:shounen_ai", label: "Shounen ai", adultContent: false },
  { id: "genre:showbiz", label: "Showbiz", adultContent: false },
  { id: "genre:slice_of_life", label: "Slice of Life", adultContent: false },
  { id: "genre:sm_bdsm", label: "SM/BDSM/SUB-DOM", adultContent: false },
  { id: "genre:space", label: "Space", adultContent: false },
  { id: "genre:sports", label: "Sports", adultContent: false },
  { id: "genre:super_power", label: "Super Power", adultContent: false },
  { id: "genre:superhero", label: "Superhero", adultContent: false },
  { id: "genre:supernatural", label: "Supernatural", adultContent: false },
  { id: "genre:survival", label: "Survival", adultContent: false },
  { id: "genre:thriller", label: "Thriller", adultContent: false },
  { id: "genre:time_travel", label: "Time Travel", adultContent: false },
  { id: "genre:tower_climbing", label: "Tower Climbing", adultContent: false },
  {
    id: "genre:traditional_games",
    label: "Traditional Games",
    adultContent: false,
  },
  { id: "genre:tragedy", label: "Tragedy", adultContent: false },
  { id: "genre:transmigration", label: "Transmigration", adultContent: false },
  { id: "genre:vampires", label: "Vampires", adultContent: false },
  { id: "genre:villainess", label: "Villainess", adultContent: false },
  { id: "genre:video_games", label: "Video Games", adultContent: false },
  {
    id: "genre:virtual_reality",
    label: "Virtual Reality",
    adultContent: false,
  },
  { id: "genre:wuxia", label: "Wuxia", adultContent: false },
  { id: "genre:xianxia", label: "Xianxia", adultContent: false },
  { id: "genre:xuanhuan", label: "Xuanhuan", adultContent: false },
  { id: "genre:yakuzas", label: "Yakuzas", adultContent: false },
  { id: "genre:zombies", label: "Zombies", adultContent: false },
];

export const STATUS_TAGS: Tag[] = [
  { id: "status:pending", label: "Pending", adultContent: false },
  { id: "status:ongoing", label: "Ongoing", adultContent: false },
  { id: "status:completed", label: "Completed", adultContent: false },
  { id: "status:hiatus", label: "Hiatus", adultContent: false },
  { id: "status:cancelled", label: "Cancelled", adultContent: false },
];

export const ORIGIN_TAGS: Tag[] = [
  { id: "origin:zh", label: "Chinese", adultContent: false },
  { id: "origin:en", label: "English", adultContent: false },
  { id: "origin:ja", label: "Japanese", adultContent: false },
  { id: "origin:ko", label: "Korean", adultContent: false },
  { id: "origin:af", label: "Afrikaans", adultContent: false },
  { id: "origin:sq", label: "Albanian", adultContent: false },
  { id: "origin:am", label: "Amharic", adultContent: false },
  { id: "origin:ar", label: "Arabic", adultContent: false },
  { id: "origin:hy", label: "Armenian", adultContent: false },
  { id: "origin:az", label: "Azerbaijani", adultContent: false },
  { id: "origin:be", label: "Belarusian", adultContent: false },
  { id: "origin:bn", label: "Bengali", adultContent: false },
  { id: "origin:bs", label: "Bosnian", adultContent: false },
  { id: "origin:bg", label: "Bulgarian", adultContent: false },
  { id: "origin:my", label: "Burmese", adultContent: false },
  { id: "origin:km", label: "Cambodian", adultContent: false },
  { id: "origin:ca", label: "Catalan", adultContent: false },
  { id: "origin:ceb", label: "Cebuano", adultContent: false },
  { id: "origin:zh_hk", label: "Chinese (Cantonese)", adultContent: false },
  { id: "origin:zh_tw", label: "Chinese (Traditional)", adultContent: false },
  { id: "origin:hr", label: "Croatian", adultContent: false },
  { id: "origin:cs", label: "Czech", adultContent: false },
  { id: "origin:da", label: "Danish", adultContent: false },
  { id: "origin:nl", label: "Dutch", adultContent: false },
  { id: "origin:en_us", label: "English (United States)", adultContent: false },
  { id: "origin:eo", label: "Esperanto", adultContent: false },
  { id: "origin:et", label: "Estonian", adultContent: false },
  { id: "origin:fo", label: "Faroese", adultContent: false },
  { id: "origin:fil", label: "Filipino", adultContent: false },
  { id: "origin:fi", label: "Finnish", adultContent: false },
  { id: "origin:fr", label: "French", adultContent: false },
  { id: "origin:ka", label: "Georgian", adultContent: false },
  { id: "origin:de", label: "German", adultContent: false },
  { id: "origin:el", label: "Greek", adultContent: false },
  { id: "origin:gn", label: "Guarani", adultContent: false },
  { id: "origin:gu", label: "Gujarati", adultContent: false },
  { id: "origin:ht", label: "Haitian Creole", adultContent: false },
  { id: "origin:ha", label: "Hausa", adultContent: false },
  { id: "origin:he", label: "Hebrew", adultContent: false },
  { id: "origin:hi", label: "Hindi", adultContent: false },
  { id: "origin:hu", label: "Hungarian", adultContent: false },
  { id: "origin:is", label: "Icelandic", adultContent: false },
  { id: "origin:ig", label: "Igbo", adultContent: false },
  { id: "origin:id", label: "Indonesian", adultContent: false },
  { id: "origin:ga", label: "Irish", adultContent: false },
  { id: "origin:it", label: "Italian", adultContent: false },
  { id: "origin:jv", label: "Javanese", adultContent: false },
  { id: "origin:kn", label: "Kannada", adultContent: false },
  { id: "origin:kk", label: "Kazakh", adultContent: false },
  { id: "origin:ku", label: "Kurdish", adultContent: false },
  { id: "origin:ky", label: "Kyrgyz", adultContent: false },
  { id: "origin:lo", label: "Laothian", adultContent: false },
  { id: "origin:lv", label: "Latvian", adultContent: false },
  { id: "origin:lt", label: "Lithuanian", adultContent: false },
  { id: "origin:lb", label: "Luxembourgish", adultContent: false },
  { id: "origin:mk", label: "Macedonian", adultContent: false },
  { id: "origin:mg", label: "Malagasy", adultContent: false },
  { id: "origin:ms", label: "Malay", adultContent: false },
  { id: "origin:ml", label: "Malayalam", adultContent: false },
  { id: "origin:mt", label: "Maltese", adultContent: false },
  { id: "origin:mi", label: "Maori", adultContent: false },
  { id: "origin:mr", label: "Marathi", adultContent: false },
  { id: "origin:mo", label: "Moldavian", adultContent: false },
  { id: "origin:mn", label: "Mongolian", adultContent: false },
  { id: "origin:ne", label: "Nepali", adultContent: false },
  { id: "origin:no", label: "Norwegian", adultContent: false },
  { id: "origin:ny", label: "Nyanja", adultContent: false },
  { id: "origin:ps", label: "Pashto", adultContent: false },
  { id: "origin:fa", label: "Persian", adultContent: false },
  { id: "origin:pl", label: "Polish", adultContent: false },
  { id: "origin:pt", label: "Portuguese", adultContent: false },
  { id: "origin:pt_br", label: "Portuguese (Brazil)", adultContent: false },
  { id: "origin:ro", label: "Romanian", adultContent: false },
  { id: "origin:rm", label: "Romansh", adultContent: false },
  { id: "origin:ru", label: "Russian", adultContent: false },
  { id: "origin:sm", label: "Samoan", adultContent: false },
  { id: "origin:sr", label: "Serbian", adultContent: false },
  { id: "origin:sh", label: "Serbo-Croatian", adultContent: false },
  { id: "origin:st", label: "Sesotho", adultContent: false },
  { id: "origin:sn", label: "Shona", adultContent: false },
  { id: "origin:sd", label: "Sindhi", adultContent: false },
  { id: "origin:si", label: "Sinhalese", adultContent: false },
  { id: "origin:sk", label: "Slovak", adultContent: false },
  { id: "origin:sl", label: "Slovenian", adultContent: false },
  { id: "origin:so", label: "Somali", adultContent: false },
  { id: "origin:es", label: "Spanish", adultContent: false },
  {
    id: "origin:es_419",
    label: "Spanish (Latin America)",
    adultContent: false,
  },
  { id: "origin:sw", label: "Swahili", adultContent: false },
  { id: "origin:sv", label: "Swedish", adultContent: false },
  { id: "origin:tg", label: "Tajik", adultContent: false },
  { id: "origin:ta", label: "Tamil", adultContent: false },
  { id: "origin:th", label: "Thai", adultContent: false },
  { id: "origin:ti", label: "Tigrinya", adultContent: false },
  { id: "origin:to", label: "Tonga", adultContent: false },
  { id: "origin:tr", label: "Turkish", adultContent: false },
  { id: "origin:tk", label: "Turkmen", adultContent: false },
  { id: "origin:uk", label: "Ukrainian", adultContent: false },
  { id: "origin:ur", label: "Urdu", adultContent: false },
  { id: "origin:uz", label: "Uzbek", adultContent: false },
  { id: "origin:vi", label: "Vietnamese", adultContent: false },
  { id: "origin:yo", label: "Yoruba", adultContent: false },
  { id: "origin:zu", label: "Zulu", adultContent: false },
  { id: "origin:_t", label: "Other", adultContent: false },
];

export const LANG_TAGS: Tag[] = [
  { id: "lang:en", label: "English", adultContent: false },
  { id: "lang:ar", label: "Arabic", adultContent: false },
  { id: "lang:bg", label: "Bulgarian", adultContent: false },
  { id: "lang:zh", label: "Chinese", adultContent: false },
  { id: "lang:cs", label: "Czech", adultContent: false },
  { id: "lang:da", label: "Danish", adultContent: false },
  { id: "lang:nl", label: "Dutch", adultContent: false },
  { id: "lang:fil", label: "Filipino", adultContent: false },
  { id: "lang:fi", label: "Finnish", adultContent: false },
  { id: "lang:fr", label: "French", adultContent: false },
  { id: "lang:de", label: "German", adultContent: false },
  { id: "lang:el", label: "Greek", adultContent: false },
  { id: "lang:he", label: "Hebrew", adultContent: false },
  { id: "lang:hi", label: "Hindi", adultContent: false },
  { id: "lang:hu", label: "Hungarian", adultContent: false },
  { id: "lang:id", label: "Indonesian", adultContent: false },
  { id: "lang:it", label: "Italian", adultContent: false },
  { id: "lang:ja", label: "Japanese", adultContent: false },
  { id: "lang:ko", label: "Korean", adultContent: false },
  { id: "lang:ms", label: "Malay", adultContent: false },
  { id: "lang:pl", label: "Polish", adultContent: false },
  { id: "lang:pt", label: "Portuguese", adultContent: false },
  { id: "lang:pt_br", label: "Portuguese (Brazil)", adultContent: false },
  { id: "lang:ro", label: "Romanian", adultContent: false },
  { id: "lang:ru", label: "Russian", adultContent: false },
  { id: "lang:es", label: "Spanish", adultContent: false },
  { id: "lang:es_419", label: "Spanish (Latin America)", adultContent: false },
  { id: "lang:sv", label: "Swedish", adultContent: false },
  { id: "lang:th", label: "Thai", adultContent: false },
  { id: "lang:tr", label: "Turkish", adultContent: false },
  { id: "lang:uk", label: "Ukrainian", adultContent: false },
  { id: "lang:vi", label: "Vietnamese", adultContent: false },
  { id: "lang:af", label: "Afrikaans", adultContent: false },
  { id: "lang:sq", label: "Albanian", adultContent: false },
  { id: "lang:am", label: "Amharic", adultContent: false },
  { id: "lang:hy", label: "Armenian", adultContent: false },
  { id: "lang:az", label: "Azerbaijani", adultContent: false },
  { id: "lang:be", label: "Belarusian", adultContent: false },
  { id: "lang:bn", label: "Bengali", adultContent: false },
  { id: "lang:bs", label: "Bosnian", adultContent: false },
  { id: "lang:my", label: "Burmese", adultContent: false },
  { id: "lang:km", label: "Cambodian", adultContent: false },
  { id: "lang:ca", label: "Catalan", adultContent: false },
  { id: "lang:ceb", label: "Cebuano", adultContent: false },
  { id: "lang:zh_hk", label: "Chinese (Cantonese)", adultContent: false },
  { id: "lang:zh_tw", label: "Chinese (Traditional)", adultContent: false },
  { id: "lang:hr", label: "Croatian", adultContent: false },
  { id: "lang:en_us", label: "English (United States)", adultContent: false },
  { id: "lang:eo", label: "Esperanto", adultContent: false },
  { id: "lang:et", label: "Estonian", adultContent: false },
  { id: "lang:fo", label: "Faroese", adultContent: false },
  { id: "lang:ka", label: "Georgian", adultContent: false },
  { id: "lang:gn", label: "Guarani", adultContent: false },
  { id: "lang:gu", label: "Gujarati", adultContent: false },
  { id: "lang:ht", label: "Haitian Creole", adultContent: false },
  { id: "lang:ha", label: "Hausa", adultContent: false },
  { id: "lang:is", label: "Icelandic", adultContent: false },
  { id: "lang:ig", label: "Igbo", adultContent: false },
  { id: "lang:ga", label: "Irish", adultContent: false },
  { id: "lang:jv", label: "Javanese", adultContent: false },
  { id: "lang:kn", label: "Kannada", adultContent: false },
  { id: "lang:kk", label: "Kazakh", adultContent: false },
  { id: "lang:ku", label: "Kurdish", adultContent: false },
  { id: "lang:ky", label: "Kyrgyz", adultContent: false },
  { id: "lang:lo", label: "Laothian", adultContent: false },
  { id: "lang:lv", label: "Latvian", adultContent: false },
  { id: "lang:lt", label: "Lithuanian", adultContent: false },
  { id: "lang:lb", label: "Luxembourgish", adultContent: false },
  { id: "lang:mk", label: "Macedonian", adultContent: false },
  { id: "lang:mg", label: "Malagasy", adultContent: false },
  { id: "lang:ml", label: "Malayalam", adultContent: false },
  { id: "lang:mt", label: "Maltese", adultContent: false },
  { id: "lang:mi", label: "Maori", adultContent: false },
  { id: "lang:mr", label: "Marathi", adultContent: false },
  { id: "lang:mo", label: "Moldavian", adultContent: false },
  { id: "lang:mn", label: "Mongolian", adultContent: false },
  { id: "lang:ne", label: "Nepali", adultContent: false },
  { id: "lang:no", label: "Norwegian", adultContent: false },
  { id: "lang:ny", label: "Nyanja", adultContent: false },
  { id: "lang:ps", label: "Pashto", adultContent: false },
  { id: "lang:fa", label: "Persian", adultContent: false },
  { id: "lang:rm", label: "Romansh", adultContent: false },
  { id: "lang:sm", label: "Samoan", adultContent: false },
  { id: "lang:sr", label: "Serbian", adultContent: false },
  { id: "lang:sh", label: "Serbo-Croatian", adultContent: false },
  { id: "lang:st", label: "Sesotho", adultContent: false },
  { id: "lang:sn", label: "Shona", adultContent: false },
  { id: "lang:sd", label: "Sindhi", adultContent: false },
  { id: "lang:si", label: "Sinhalese", adultContent: false },
  { id: "lang:sk", label: "Slovak", adultContent: false },
  { id: "lang:sl", label: "Slovenian", adultContent: false },
  { id: "lang:so", label: "Somali", adultContent: false },
  { id: "lang:sw", label: "Swahili", adultContent: false },
  { id: "lang:tg", label: "Tajik", adultContent: false },
  { id: "lang:ta", label: "Tamil", adultContent: false },
  { id: "lang:ti", label: "Tigrinya", adultContent: false },
  { id: "lang:to", label: "Tonga", adultContent: false },
  { id: "lang:tk", label: "Turkmen", adultContent: false },
  { id: "lang:ur", label: "Urdu", adultContent: false },
  { id: "lang:uz", label: "Uzbek", adultContent: false },
  { id: "lang:yo", label: "Yoruba", adultContent: false },
  { id: "lang:zu", label: "Zulu", adultContent: false },
  { id: "lang:_t", label: "Other", adultContent: false },
];

export const SORTERS: SearchSort[] = [
  { label: "Most Views Totally", id: "views_a" },
  { label: "Most Views 365 days", id: "views_y" },
  { label: "Most Views 30 days", id: "views_m" },
  { label: "Most Views 7 days", id: "views_w" },
  { label: "Most Views 24 hours", id: "views_d" },
  { label: "Most Views 60 minutes", id: "views_h" },
  { label: "Z-A", id: "title" },
  { label: "Last Updated", id: "update" },
  { label: "Newest Added", id: "create" },
];

export const getAllGenreTags = () => {
  return [
    ...GENERIC_TAGS,
    ...ADULT_TAGS,
    ...CONTENT_TYPE_TAGS,
    ...DEMOGRAPHIC_TAGS,
  ];
};
