import { SearchSort, Tag } from "@suwatte/daisuke";

export const CONTENT_TYPE_TAGS: Tag[] = [
  { id: "artbook", label: "Artbook", adultContent: false },
  { id: "cartoon", label: "Cartoon", adultContent: false },
  { id: "comic", label: "Comic", adultContent: false },
  { id: "doujinshi", label: "Doujinshi", adultContent: false },
  { id: "imageset", label: "Imageset", adultContent: false },
  { id: "manga", label: "Manga", adultContent: false },
  { id: "manhua", label: "Manhua", adultContent: false },
  { id: "manhwa", label: "Manhwa", adultContent: false },
  { id: "webtoon", label: "Webtoon", adultContent: false },
  { id: "western", label: "Western", adultContent: false },
];

export const DEMOGRAPHIC_TAGS: Tag[] = [
  { id: "shoujo", label: "Shoujo(G)", adultContent: false },
  { id: "shounen", label: "Shounen(B)", adultContent: false },
  { id: "josei", label: "Josei(W)", adultContent: false },
  { id: "seinen", label: "Seinen(M)", adultContent: false },
  { id: "yuri", label: "Yuri(GL)", adultContent: false },
  { id: "yaoi", label: "Yaoi(BL)", adultContent: false },
  { id: "futa", label: "Futa(WL)", adultContent: true },
  { id: "bara", label: "Bara(ML)", adultContent: true },
];

export const ADULT_TAGS: Tag[] = [
  { id: "gore", label: "Gore", adultContent: true },
  { id: "bloody", label: "Bloody", adultContent: true },
  { id: "violence", label: "Violence", adultContent: true },
  { id: "ecchi", label: "Ecchi", adultContent: true },
  { id: "adult", label: "Adult", adultContent: true },
  { id: "mature", label: "Mature", adultContent: true },
  { id: "smut", label: "Smut", adultContent: true },
  { id: "hentai", label: "Hentai", adultContent: true },
];

export const GENERIC_TAGS: Tag[] = [
  { id: "_4_koma", label: "4-Koma", adultContent: false },
  { id: "action", label: "Action", adultContent: false },
  { id: "adaptation", label: "Adaptation", adultContent: false },
  { id: "adventure", label: "Adventure", adultContent: false },
  { id: "age_gap", label: "Age Gap", adultContent: false },
  { id: "aliens", label: "Aliens", adultContent: false },
  { id: "animals", label: "Animals", adultContent: false },
  { id: "anthology", label: "Anthology", adultContent: false },
  { id: "beasts", label: "Beasts", adultContent: false },
  { id: "bodyswap", label: "Bodyswap", adultContent: false },
  { id: "cars", label: "Cars", adultContent: false },
  {
    id: "cheating_infidelity",
    label: "Cheating/Infidelity",
    adultContent: false,
  },
  {
    id: "childhood_friends",
    label: "Childhood Friends",
    adultContent: false,
  },
  { id: "college_life", label: "College life ", adultContent: false },
  { id: "comedy", label: "Comedy", adultContent: false },
  {
    id: "contest_winning",
    label: "Contest winning",
    adultContent: false,
  },
  { id: "cooking", label: "Cooking", adultContent: false },
  { id: "crime", label: "Crime", adultContent: false },
  { id: "crossdressing", label: "Crossdressing", adultContent: false },
  { id: "delinquents", label: "Delinquents", adultContent: false },
  { id: "dementia", label: "Dementia", adultContent: false },
  { id: "demons", label: "Demons", adultContent: false },
  { id: "drama", label: "Drama", adultContent: false },
  { id: "dungeons", label: "Dungeons", adultContent: false },
  {
    id: "emperor_daughte",
    label: "Emperor's daughte",
    adultContent: false,
  },
  { id: "fantasy", label: "Fantasy", adultContent: false },
  { id: "fan_colored", label: "Fan-Colored", adultContent: false },
  { id: "fetish", label: "Fetish", adultContent: false },
  { id: "full_color", label: "Full Color", adultContent: false },
  { id: "game", label: "Game", adultContent: false },
  { id: "gender_bender", label: "Gender Bender", adultContent: false },
  { id: "genderswap", label: "Genderswap", adultContent: false },
  { id: "ghosts", label: "Ghosts", adultContent: false },
  { id: "gyaru", label: "Gyaru", adultContent: false },
  { id: "harem", label: "Harem", adultContent: false },
  { id: "harlequin", label: "Harlequin", adultContent: false },
  { id: "historical", label: "Historical", adultContent: false },
  { id: "horror", label: "Horror", adultContent: false },
  { id: "incest", label: "Incest", adultContent: false },
  { id: "isekai", label: "Isekai", adultContent: false },
  { id: "kids", label: "Kids", adultContent: false },
  { id: "loli", label: "Loli", adultContent: false },
  { id: "magic", label: "Magic", adultContent: false },
  { id: "magical_girls", label: "Magical Girls", adultContent: false },
  { id: "martial_arts", label: "Martial Arts", adultContent: false },
  { id: "mecha", label: "Mecha", adultContent: false },
  { id: "medical", label: "Medical", adultContent: false },
  { id: "military", label: "Military", adultContent: false },
  { id: "monster_girls", label: "Monster Girls", adultContent: false },
  { id: "monsters", label: "Monsters", adultContent: false },
  { id: "music", label: "Music", adultContent: false },
  { id: "mystery", label: "Mystery", adultContent: false },
  { id: "netorare", label: "Netorare/NTR", adultContent: false },
  { id: "ninja", label: "Ninja", adultContent: false },
  { id: "office_workers", label: "Office Workers", adultContent: false },
  { id: "omegaverse", label: "Omegaverse", adultContent: false },
  { id: "oneshot", label: "Oneshot", adultContent: false },
  { id: "parody", label: "parody", adultContent: false },
  { id: "philosophical", label: "Philosophical", adultContent: false },
  { id: "police", label: "Police", adultContent: false },
  {
    id: "post_apocalyptic",
    label: "Post-Apocalyptic",
    adultContent: false,
  },
  { id: "psychological", label: "Psychological", adultContent: false },
  { id: "regression", label: "Regression", adultContent: false },
  { id: "reincarnation", label: "Reincarnation", adultContent: false },
  { id: "reverse_harem", label: "Reverse Harem", adultContent: false },
  { id: "revenge", label: "Revenge", adultContent: false },
  { id: "reverse_isekai", label: "Reverse Isekai ", adultContent: false },
  { id: "romance", label: "Romance", adultContent: false },
  { id: "royal_family", label: "Royal family", adultContent: false },
  { id: "royalty", label: "Royalty", adultContent: false },
  { id: "samurai", label: "Samurai", adultContent: false },
  { id: "school_life", label: "School Life", adultContent: false },
  { id: "sci_fi", label: "Sci-Fi", adultContent: false },
  { id: "shota", label: "Shota", adultContent: false },
  { id: "shoujo_ai", label: "Shoujo ai", adultContent: false },
  { id: "shounen_ai", label: "Shounen ai", adultContent: false },
  { id: "showbiz", label: "Showbiz", adultContent: false },
  { id: "slice_of_life", label: "Slice of Life", adultContent: false },
  { id: "sm_bdsm", label: "SM/BDSM/SUB-DOM", adultContent: false },
  { id: "space", label: "Space", adultContent: false },
  { id: "sports", label: "Sports", adultContent: false },
  { id: "super_power", label: "Super Power", adultContent: false },
  { id: "superhero", label: "Superhero", adultContent: false },
  { id: "supernatural", label: "Supernatural", adultContent: false },
  { id: "survival", label: "Survival", adultContent: false },
  { id: "thriller", label: "Thriller", adultContent: false },
  { id: "time_travel", label: "Time Travel", adultContent: false },
  { id: "tower_climbing", label: "Tower Climbing", adultContent: false },
  {
    id: "traditional_games",
    label: "Traditional Games",
    adultContent: false,
  },
  { id: "tragedy", label: "Tragedy", adultContent: false },
  { id: "transmigration", label: "Transmigration", adultContent: false },
  { id: "vampires", label: "Vampires", adultContent: false },
  { id: "villainess", label: "Villainess", adultContent: false },
  { id: "video_games", label: "Video Games", adultContent: false },
  {
    id: "virtual_reality",
    label: "Virtual Reality",
    adultContent: false,
  },
  { id: "wuxia", label: "Wuxia", adultContent: false },
  { id: "xianxia", label: "Xianxia", adultContent: false },
  { id: "xuanhuan", label: "Xuanhuan", adultContent: false },
  { id: "yakuzas", label: "Yakuzas", adultContent: false },
  { id: "zombies", label: "Zombies", adultContent: false },
];

export const STATUS_TAGS: Tag[] = [
  { id: "pending", label: "Pending", adultContent: false },
  { id: "ongoing", label: "Ongoing", adultContent: false },
  { id: "completed", label: "Completed", adultContent: false },
  { id: "hiatus", label: "Hiatus", adultContent: false },
  { id: "cancelled", label: "Cancelled", adultContent: false },
];

export const ORIGIN_TAGS: Tag[] = [
  { id: "zh", label: "Chinese", adultContent: false },
  { id: "en", label: "English", adultContent: false },
  { id: "ja", label: "Japanese", adultContent: false },
  { id: "ko", label: "Korean", adultContent: false },
  { id: "af", label: "Afrikaans", adultContent: false },
  { id: "sq", label: "Albanian", adultContent: false },
  { id: "am", label: "Amharic", adultContent: false },
  { id: "ar", label: "Arabic", adultContent: false },
  { id: "hy", label: "Armenian", adultContent: false },
  { id: "az", label: "Azerbaijani", adultContent: false },
  { id: "be", label: "Belarusian", adultContent: false },
  { id: "bn", label: "Bengali", adultContent: false },
  { id: "bs", label: "Bosnian", adultContent: false },
  { id: "bg", label: "Bulgarian", adultContent: false },
  { id: "my", label: "Burmese", adultContent: false },
  { id: "km", label: "Cambodian", adultContent: false },
  { id: "ca", label: "Catalan", adultContent: false },
  { id: "ceb", label: "Cebuano", adultContent: false },
  { id: "zh_hk", label: "Chinese (Cantonese)", adultContent: false },
  { id: "zh_tw", label: "Chinese (Traditional)", adultContent: false },
  { id: "hr", label: "Croatian", adultContent: false },
  { id: "cs", label: "Czech", adultContent: false },
  { id: "da", label: "Danish", adultContent: false },
  { id: "nl", label: "Dutch", adultContent: false },
  { id: "en_us", label: "English (United States)", adultContent: false },
  { id: "eo", label: "Esperanto", adultContent: false },
  { id: "et", label: "Estonian", adultContent: false },
  { id: "fo", label: "Faroese", adultContent: false },
  { id: "fil", label: "Filipino", adultContent: false },
  { id: "fi", label: "Finnish", adultContent: false },
  { id: "fr", label: "French", adultContent: false },
  { id: "ka", label: "Georgian", adultContent: false },
  { id: "de", label: "German", adultContent: false },
  { id: "el", label: "Greek", adultContent: false },
  { id: "gn", label: "Guarani", adultContent: false },
  { id: "gu", label: "Gujarati", adultContent: false },
  { id: "ht", label: "Haitian Creole", adultContent: false },
  { id: "ha", label: "Hausa", adultContent: false },
  { id: "he", label: "Hebrew", adultContent: false },
  { id: "hi", label: "Hindi", adultContent: false },
  { id: "hu", label: "Hungarian", adultContent: false },
  { id: "is", label: "Icelandic", adultContent: false },
  { id: "ig", label: "Igbo", adultContent: false },
  { id: "id", label: "Indonesian", adultContent: false },
  { id: "ga", label: "Irish", adultContent: false },
  { id: "it", label: "Italian", adultContent: false },
  { id: "jv", label: "Javanese", adultContent: false },
  { id: "kn", label: "Kannada", adultContent: false },
  { id: "kk", label: "Kazakh", adultContent: false },
  { id: "ku", label: "Kurdish", adultContent: false },
  { id: "ky", label: "Kyrgyz", adultContent: false },
  { id: "lo", label: "Laothian", adultContent: false },
  { id: "lv", label: "Latvian", adultContent: false },
  { id: "lt", label: "Lithuanian", adultContent: false },
  { id: "lb", label: "Luxembourgish", adultContent: false },
  { id: "mk", label: "Macedonian", adultContent: false },
  { id: "mg", label: "Malagasy", adultContent: false },
  { id: "ms", label: "Malay", adultContent: false },
  { id: "ml", label: "Malayalam", adultContent: false },
  { id: "mt", label: "Maltese", adultContent: false },
  { id: "mi", label: "Maori", adultContent: false },
  { id: "mr", label: "Marathi", adultContent: false },
  { id: "mo", label: "Moldavian", adultContent: false },
  { id: "mn", label: "Mongolian", adultContent: false },
  { id: "ne", label: "Nepali", adultContent: false },
  { id: "no", label: "Norwegian", adultContent: false },
  { id: "ny", label: "Nyanja", adultContent: false },
  { id: "ps", label: "Pashto", adultContent: false },
  { id: "fa", label: "Persian", adultContent: false },
  { id: "pl", label: "Polish", adultContent: false },
  { id: "pt", label: "Portuguese", adultContent: false },
  { id: "pt_br", label: "Portuguese (Brazil)", adultContent: false },
  { id: "ro", label: "Romanian", adultContent: false },
  { id: "rm", label: "Romansh", adultContent: false },
  { id: "ru", label: "Russian", adultContent: false },
  { id: "sm", label: "Samoan", adultContent: false },
  { id: "sr", label: "Serbian", adultContent: false },
  { id: "sh", label: "Serbo-Croatian", adultContent: false },
  { id: "st", label: "Sesotho", adultContent: false },
  { id: "sn", label: "Shona", adultContent: false },
  { id: "sd", label: "Sindhi", adultContent: false },
  { id: "si", label: "Sinhalese", adultContent: false },
  { id: "sk", label: "Slovak", adultContent: false },
  { id: "sl", label: "Slovenian", adultContent: false },
  { id: "so", label: "Somali", adultContent: false },
  { id: "es", label: "Spanish", adultContent: false },
  {
    id: "es_419",
    label: "Spanish (Latin America)",
    adultContent: false,
  },
  { id: "sw", label: "Swahili", adultContent: false },
  { id: "sv", label: "Swedish", adultContent: false },
  { id: "tg", label: "Tajik", adultContent: false },
  { id: "ta", label: "Tamil", adultContent: false },
  { id: "th", label: "Thai", adultContent: false },
  { id: "ti", label: "Tigrinya", adultContent: false },
  { id: "to", label: "Tonga", adultContent: false },
  { id: "tr", label: "Turkish", adultContent: false },
  { id: "tk", label: "Turkmen", adultContent: false },
  { id: "uk", label: "Ukrainian", adultContent: false },
  { id: "ur", label: "Urdu", adultContent: false },
  { id: "uz", label: "Uzbek", adultContent: false },
  { id: "vi", label: "Vietnamese", adultContent: false },
  { id: "yo", label: "Yoruba", adultContent: false },
  { id: "zu", label: "Zulu", adultContent: false },
  { id: "_t", label: "Other", adultContent: false },
];

export const LANG_TAGS: Tag[] = [
  { id: "en", label: "English", adultContent: false },
  { id: "ar", label: "Arabic", adultContent: false },
  { id: "bg", label: "Bulgarian", adultContent: false },
  { id: "zh", label: "Chinese", adultContent: false },
  { id: "cs", label: "Czech", adultContent: false },
  { id: "da", label: "Danish", adultContent: false },
  { id: "nl", label: "Dutch", adultContent: false },
  { id: "fil", label: "Filipino", adultContent: false },
  { id: "fi", label: "Finnish", adultContent: false },
  { id: "fr", label: "French", adultContent: false },
  { id: "de", label: "German", adultContent: false },
  { id: "el", label: "Greek", adultContent: false },
  { id: "he", label: "Hebrew", adultContent: false },
  { id: "hi", label: "Hindi", adultContent: false },
  { id: "hu", label: "Hungarian", adultContent: false },
  { id: "id", label: "Indonesian", adultContent: false },
  { id: "it", label: "Italian", adultContent: false },
  { id: "ja", label: "Japanese", adultContent: false },
  { id: "ko", label: "Korean", adultContent: false },
  { id: "ms", label: "Malay", adultContent: false },
  { id: "pl", label: "Polish", adultContent: false },
  { id: "pt", label: "Portuguese", adultContent: false },
  { id: "pt_br", label: "Portuguese (Brazil)", adultContent: false },
  { id: "ro", label: "Romanian", adultContent: false },
  { id: "ru", label: "Russian", adultContent: false },
  { id: "es", label: "Spanish", adultContent: false },
  { id: "es_419", label: "Spanish (Latin America)", adultContent: false },
  { id: "sv", label: "Swedish", adultContent: false },
  { id: "th", label: "Thai", adultContent: false },
  { id: "tr", label: "Turkish", adultContent: false },
  { id: "uk", label: "Ukrainian", adultContent: false },
  { id: "vi", label: "Vietnamese", adultContent: false },
  { id: "af", label: "Afrikaans", adultContent: false },
  { id: "sq", label: "Albanian", adultContent: false },
  { id: "am", label: "Amharic", adultContent: false },
  { id: "hy", label: "Armenian", adultContent: false },
  { id: "az", label: "Azerbaijani", adultContent: false },
  { id: "be", label: "Belarusian", adultContent: false },
  { id: "bn", label: "Bengali", adultContent: false },
  { id: "bs", label: "Bosnian", adultContent: false },
  { id: "my", label: "Burmese", adultContent: false },
  { id: "km", label: "Cambodian", adultContent: false },
  { id: "ca", label: "Catalan", adultContent: false },
  { id: "ceb", label: "Cebuano", adultContent: false },
  { id: "zh_hk", label: "Chinese (Cantonese)", adultContent: false },
  { id: "zh_tw", label: "Chinese (Traditional)", adultContent: false },
  { id: "hr", label: "Croatian", adultContent: false },
  { id: "en_us", label: "English (United States)", adultContent: false },
  { id: "eo", label: "Esperanto", adultContent: false },
  { id: "et", label: "Estonian", adultContent: false },
  { id: "fo", label: "Faroese", adultContent: false },
  { id: "ka", label: "Georgian", adultContent: false },
  { id: "gn", label: "Guarani", adultContent: false },
  { id: "gu", label: "Gujarati", adultContent: false },
  { id: "ht", label: "Haitian Creole", adultContent: false },
  { id: "ha", label: "Hausa", adultContent: false },
  { id: "is", label: "Icelandic", adultContent: false },
  { id: "ig", label: "Igbo", adultContent: false },
  { id: "ga", label: "Irish", adultContent: false },
  { id: "jv", label: "Javanese", adultContent: false },
  { id: "kn", label: "Kannada", adultContent: false },
  { id: "kk", label: "Kazakh", adultContent: false },
  { id: "ku", label: "Kurdish", adultContent: false },
  { id: "ky", label: "Kyrgyz", adultContent: false },
  { id: "lo", label: "Laothian", adultContent: false },
  { id: "lv", label: "Latvian", adultContent: false },
  { id: "lt", label: "Lithuanian", adultContent: false },
  { id: "lb", label: "Luxembourgish", adultContent: false },
  { id: "mk", label: "Macedonian", adultContent: false },
  { id: "mg", label: "Malagasy", adultContent: false },
  { id: "ml", label: "Malayalam", adultContent: false },
  { id: "mt", label: "Maltese", adultContent: false },
  { id: "mi", label: "Maori", adultContent: false },
  { id: "mr", label: "Marathi", adultContent: false },
  { id: "mo", label: "Moldavian", adultContent: false },
  { id: "mn", label: "Mongolian", adultContent: false },
  { id: "ne", label: "Nepali", adultContent: false },
  { id: "no", label: "Norwegian", adultContent: false },
  { id: "ny", label: "Nyanja", adultContent: false },
  { id: "ps", label: "Pashto", adultContent: false },
  { id: "fa", label: "Persian", adultContent: false },
  { id: "rm", label: "Romansh", adultContent: false },
  { id: "sm", label: "Samoan", adultContent: false },
  { id: "sr", label: "Serbian", adultContent: false },
  { id: "sh", label: "Serbo-Croatian", adultContent: false },
  { id: "st", label: "Sesotho", adultContent: false },
  { id: "sn", label: "Shona", adultContent: false },
  { id: "sd", label: "Sindhi", adultContent: false },
  { id: "si", label: "Sinhalese", adultContent: false },
  { id: "sk", label: "Slovak", adultContent: false },
  { id: "sl", label: "Slovenian", adultContent: false },
  { id: "so", label: "Somali", adultContent: false },
  { id: "sw", label: "Swahili", adultContent: false },
  { id: "tg", label: "Tajik", adultContent: false },
  { id: "ta", label: "Tamil", adultContent: false },
  { id: "ti", label: "Tigrinya", adultContent: false },
  { id: "to", label: "Tonga", adultContent: false },
  { id: "tk", label: "Turkmen", adultContent: false },
  { id: "ur", label: "Urdu", adultContent: false },
  { id: "uz", label: "Uzbek", adultContent: false },
  { id: "yo", label: "Yoruba", adultContent: false },
  { id: "zu", label: "Zulu", adultContent: false },
  { id: "_t", label: "Other", adultContent: false },
];

export const SORTERS: SearchSort[] = [
  { label: "Most Views Totally", id: "views_a" },
  { label: "Most Views 365 days", id: "views_y" },
  { label: "Most Views 30 days", id: "views_m" },
  { label: "Most Views 7 days", id: "views_w" },
  { label: "Most Views 24 hours", id: "views_d" },
  { label: "Most Views 60 minutes", id: "views_h" },
  { label: "Z-A", id: "title" },
  { label: "Last Updated", id: "update" },
  { label: "Newest Added", id: "create" },
];

export const getAllGenreTags = () => {
  return [
    ...GENERIC_TAGS,
    ...ADULT_TAGS,
    ...CONTENT_TYPE_TAGS,
    ...DEMOGRAPHIC_TAGS,
  ];
};
